---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: abhojdkp-dkp
  name: abhojdkp-dkp-md-0
  namespace: default
spec:
  clusterName: abhojdkp-dkp
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: abhojdkp-dkp
      cluster.x-k8s.io/deployment-name: abhojdkp-dkp-md-0
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: abhojdkp-dkp
        cluster.x-k8s.io/deployment-name: abhojdkp-dkp-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: abhojdkp-dkp-md-0
      clusterName: abhojdkp-dkp
      infrastructureRef:
        apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
        kind: PreprovisionedMachineTemplate
        name: abhojdkp-dkp-md-0
      version: v1.24.6
