---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    konvoy.d2iq.io/cluster-name: abhojdkp-dkp
    konvoy.d2iq.io/cni: calico
    konvoy.d2iq.io/csi: local-volume-provisioner
    konvoy.d2iq.io/loadbalancer: metallb
    konvoy.d2iq.io/osHint: flatcar
    konvoy.d2iq.io/provider: preprovisioned
  name: abhojdkp-dkp
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneEndpoint:
    host: ""
    port: 0
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: abhojdkp-dkp-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
    kind: PreprovisionedCluster
    name: abhojdkp-dkp
    namespace: default