---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  labels:
    app: metallb
    konvoy.d2iq.io/cluster-name: abhojdkp-dkp
  name: metallb-abhojdkp-dkp
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      konvoy.d2iq.io/loadbalancer: metallb
  resources:
  - kind: ConfigMap
    name: metallb-installation-abhojdkp-dkp
  strategy: ApplyAlways
---
apiVersion: v1
data:
  custom-resources.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: metallb-system
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: controller
      namespace: metallb-system
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: speaker
      namespace: metallb-system
    ---
    apiVersion: policy/v1beta1
    kind: PodSecurityPolicy
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: controller
    spec:
      allowPrivilegeEscalation: false
      allowedCapabilities: []
      allowedHostPaths: []
      defaultAddCapabilities: []
      defaultAllowPrivilegeEscalation: false
      fsGroup:
        ranges:
        - max: 65535
          min: 1
        rule: MustRunAs
      hostIPC: false
      hostNetwork: false
      hostPID: false
      privileged: false
      readOnlyRootFilesystem: true
      requiredDropCapabilities:
      - ALL
      runAsUser:
        ranges:
        - max: 65535
          min: 1
        rule: MustRunAs
      seLinux:
        rule: RunAsAny
      supplementalGroups:
        ranges:
        - max: 65535
          min: 1
        rule: MustRunAs
      volumes:
      - configMap
      - secret
      - emptyDir
    ---
    apiVersion: policy/v1beta1
    kind: PodSecurityPolicy
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: speaker
    spec:
      allowPrivilegeEscalation: false
      allowedCapabilities:
      - NET_RAW
      allowedHostPaths: []
      defaultAddCapabilities: []
      defaultAllowPrivilegeEscalation: false
      fsGroup:
        rule: RunAsAny
      hostIPC: false
      hostNetwork: true
      hostPID: false
      hostPorts:
      - max: 7472
        min: 7472
      - max: 7946
        min: 7946
      privileged: true
      readOnlyRootFilesystem: true
      requiredDropCapabilities:
      - ALL
      runAsUser:
        rule: RunAsAny
      seLinux:
        rule: RunAsAny
      supplementalGroups:
        rule: RunAsAny
      volumes:
      - configMap
      - secret
      - emptyDir
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: config-watcher
      namespace: metallb-system
    rules:
    - apiGroups:
      - ""
      resources:
      - configmaps
      verbs:
      - get
      - list
      - watch
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: controller
      namespace: metallb-system
    rules:
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - create
    - apiGroups:
      - ""
      resourceNames:
      - memberlist
      resources:
      - secrets
      verbs:
      - list
    - apiGroups:
      - apps
      resourceNames:
      - controller
      resources:
      - deployments
      verbs:
      - get
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: pod-lister
      namespace: metallb-system
    rules:
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - list
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: metallb-system:controller
    rules:
    - apiGroups:
      - ""
      resources:
      - services
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - services/status
      verbs:
      - update
    - apiGroups:
      - ""
      resources:
      - events
      verbs:
      - create
      - patch
    - apiGroups:
      - policy
      resourceNames:
      - controller
      resources:
      - podsecuritypolicies
      verbs:
      - use
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: metallb-system:speaker
    rules:
    - apiGroups:
      - ""
      resources:
      - services
      - endpoints
      - nodes
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - discovery.k8s.io
      resources:
      - endpointslices
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - events
      verbs:
      - create
      - patch
    - apiGroups:
      - policy
      resourceNames:
      - speaker
      resources:
      - podsecuritypolicies
      verbs:
      - use
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: config-watcher
      namespace: metallb-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: config-watcher
    subjects:
    - kind: ServiceAccount
      name: controller
      namespace: metallb-system
    - kind: ServiceAccount
      name: speaker
      namespace: metallb-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: controller
      namespace: metallb-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: controller
    subjects:
    - kind: ServiceAccount
      name: controller
      namespace: metallb-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: pod-lister
      namespace: metallb-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: pod-lister
    subjects:
    - kind: ServiceAccount
      name: speaker
      namespace: metallb-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: metallb-system:controller
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: metallb-system:controller
    subjects:
    - kind: ServiceAccount
      name: controller
      namespace: metallb-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      labels:
        app: metallb
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: metallb-system:speaker
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: metallb-system:speaker
    subjects:
    - kind: ServiceAccount
      name: speaker
      namespace: metallb-system
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: metallb
        component: controller
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: controller
      namespace: metallb-system
    spec:
      revisionHistoryLimit: 3
      selector:
        matchLabels:
          app: metallb
          component: controller
          konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      template:
        metadata:
          annotations:
            prometheus.io/port: "7472"
            prometheus.io/scrape: "true"
          labels:
            app: metallb
            component: controller
            konvoy.d2iq.io/cluster-name: abhojdkp-dkp
        spec:
          containers:
          - args:
            - --port=7472
            - --config=config
            - --log-level=info
            env:
            - name: METALLB_ML_SECRET_NAME
              value: memberlist
            - name: METALLB_DEPLOYMENT
              value: controller
            image: quay.io/metallb/controller:v0.12.1
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /metrics
                port: monitoring
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            name: controller
            ports:
            - containerPort: 7472
              name: monitoring
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /metrics
                port: monitoring
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - all
              readOnlyRootFilesystem: true
          nodeSelector:
            kubernetes.io/os: linux
          securityContext:
            fsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
          serviceAccountName: controller
          terminationGracePeriodSeconds: 0
    ---
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      labels:
        app: metallb
        component: speaker
        konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      name: speaker
      namespace: metallb-system
    spec:
      selector:
        matchLabels:
          app: metallb
          component: speaker
          konvoy.d2iq.io/cluster-name: abhojdkp-dkp
      template:
        metadata:
          annotations:
            prometheus.io/port: "7472"
            prometheus.io/scrape: "true"
          labels:
            app: metallb
            component: speaker
            konvoy.d2iq.io/cluster-name: abhojdkp-dkp
        spec:
          containers:
          - args:
            - --port=7472
            - --config=config
            - --log-level=info
            env:
            - name: METALLB_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: METALLB_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: METALLB_ML_BIND_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: METALLB_ML_LABELS
              value: app=metallb,component=speaker
            - name: METALLB_ML_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: memberlist
            image: quay.io/metallb/speaker:v0.12.1
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /metrics
                port: monitoring
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            name: speaker
            ports:
            - containerPort: 7472
              name: monitoring
            - containerPort: 7946
              name: memberlist-tcp
            - containerPort: 7946
              name: memberlist-udp
              protocol: UDP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /metrics
                port: monitoring
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                - NET_RAW
                drop:
                - ALL
              readOnlyRootFilesystem: true
          hostNetwork: true
          nodeSelector:
            kubernetes.io/os: linux
          serviceAccountName: speaker
          terminationGracePeriodSeconds: 2
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
            operator: Exists
kind: ConfigMap
metadata:
  labels:
    app: metallb
    konvoy.d2iq.io/cluster-name: abhojdkp-dkp
  name: metallb-installation-abhojdkp-dkp
  namespace: default
